### ISSUE TITLE
Kinectgrabber is not running in win32 configuration

### ISSUE THREAD

**Issue by sujithrobinson** [UnaNancyOwen/KinectGrabber#17]
Hi,

I have couple of doubts regarding usage of kinectgrabber inside my win32 application.

1. When i compile kinectgrabber in win32 configuration, it is giving this error 
LNK1112: module machine type 'x64' conflicts with target machine type 'X86'.

2. I was working on win32 application, i want to include grabber functionality icp for merging and aligning two pointclouds inside my win32 application in my own viewport. I need to pass pointclouds from my win32 application inside kinectgrabber. 

my system configuration:
windows 8.1
kinect for windows sdk2.0
visual studio 2012

Please suggest me what function can i use to achieve this.

Thanks
Sujith

**Comment by UnaNancyOwen** [comment]
Hi sujithrobinson,

Please tell us about the situation in detail.
It will help to solve the problem.  

* How did you install the PCL?
If you used All-in-one installer, Please tell your version that installed PCL All-in-one Installer.   (“MSVC2012 Win32″ or “MSVC2012 x64″)

* Please tell Visual Studio build log.
(It is the text that is displayed after build in Output window.)

**Comment by sujithrobinson** [comment]
Thanks UnaNancyOwen,

Yes, you are right i have installed  MSVC2012 X64.So now i am downloading MSVC2012 Win32 and will check it and let you know.

**Comment by UnaNancyOwen** [comment]
If you installed PCL 1.7.2 All-in-one Installer "MSVC2013 x64", You need set the target platform of your project to “x64″ in Visual Studio.
(If you installed "MSVC2013 Win32", It is all right with the default settings.)

Please refer to the following.
[How to: Configure Visual C++ Projects to Target 64-Bit Platforms | MSDN Library](https://msdn.microsoft.com/en-US/library/9yb4317s(v=vs.110).aspx)

**Comment by sujithrobinson** [comment]
Thanks UnaNancyOwen,
Now i could compile pcl1.7.2 in my win32 application.Again i caught up in another error,


i have used pcl1.7.2 for my win32 apps and passed my colorbuffer and depthbuffer obtained from my kinect v2 sensor to convertRGBDepthToPointXYZRGB() of kinectv2_grabber application.I get the cloud points,but it is returning only 4000 bytes.Actually my colorbuffer is of size 2073600(1920*1080).
So here i am passing my colorbuffer and depthbuffer into kinect2_grabber function:
```
UINT16*	pDepthBuffer;
BYTE*	pColorBuffer;

grabber->signal_PointXYZRGB->operator()( cloudFirst= grabber->convertRGBDepthToPointXYZRGB( reinterpret_cast<RGBQUAD*>(pColorBuffer),pDepthBuffer) );
```
This is how i am receving the pointcloud data according to my logic:

```
BYTE*	pColorBuffer;
pColorBuffer=reinterpret_cast<BYTE*>(&cloudFirst);
```
so i will display point cloud like this,
```
for (int i = 0; i < 1920; i++)
	{
	      for (int j = 0; j < 1080; j++)
		   {
		 	  int colorIndex = i + (j * 1920);
              glColor4ub(pColorBuffer[4 * colorIndex], pColorBuffer[4 * colorIndex + 1],pColorBuffer[4 * colorIndex + 2], pColorBuffer[4 * colorIndex + 3]);
              glVertex3f(xx, -yy, rPt.Z);	//this is my depth values of pointcloud
      	   }
	  }
```

since i couldn't get full color bytes the above loop results in error.

**Please suggest me how can i get full color bytes.**

Thanks
Sujith

**Comment by UnaNancyOwen** [comment]
Probably, Your usage is incorrect. 
This Grabber is derived class that derived from pcl::Grabber.
How to use this Grabber, Please refer to the [sample](https://github.com/UnaNancyOwen/KinectGrabber/tree/Kinect2Grabber/Sample) and [official tutorials](http://pointclouds.org/documentation/tutorials/openni_grabber.php).

Incidentally, The Point Cloud size retrieved using Kinect2Grabber is 512x424, and format is pcl::PointXYZRGB.
The Point Cloud size is 512x424, because it is based on Depth data,
Alpha channel is not included in the Point Cloud, because Alpha channel has been destroyed in Grabber.

I think, You need to learn about pcl::PointCloud.
It can learn in the official [documents](http://pointclouds.org/documentation/) (API reference, tutorials).
If you have more questions, I recommend that you post to the PCL [mailing list](http://www.pcl-users.org/).
